// Authoritative Lifecycle States & State Machine for ARIA Coding Engine

const TASK_STATES = Object.freeze({
  CREATED: "CREATED",
  CLASSIFIED: "CLASSIFIED",
  DISCOVERING: "DISCOVERING",
  RESEARCHING: "RESEARCHING",
  PLANNING: "PLANNING",
  PLAN_VALIDATED: "PLAN_VALIDATED",
  EXECUTING: "EXECUTING",
  TESTING: "TESTING",
  REVIEWING: "REVIEWING",
  REPAIRING: "REPAIRING",
  VERIFYING: "VERIFYING",
  COMPLETED: "COMPLETED",
  BLOCKED: "BLOCKED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  PAUSED: "PAUSED",
});

const TERMINAL_STATES = new Set([
  TASK_STATES.COMPLETED,
  TASK_STATES.FAILED,
  TASK_STATES.CANCELLED,
]);

// Valid transitions mapping
const ALLOWED_TRANSITIONS = new Map([
  [TASK_STATES.CREATED, new Set([TASK_STATES.CLASSIFIED, TASK_STATES.CANCELLED, TASK_STATES.FAILED])],
  [TASK_STATES.CLASSIFIED, new Set([TASK_STATES.DISCOVERING, TASK_STATES.CANCELLED, TASK_STATES.FAILED])],
  [TASK_STATES.DISCOVERING, new Set([TASK_STATES.RESEARCHING, TASK_STATES.PLANNING, TASK_STATES.CANCELLED, TASK_STATES.FAILED, TASK_STATES.BLOCKED])],
  [TASK_STATES.RESEARCHING, new Set([TASK_STATES.PLANNING, TASK_STATES.CANCELLED, TASK_STATES.FAILED, TASK_STATES.BLOCKED])],
  [TASK_STATES.PLANNING, new Set([TASK_STATES.PLAN_VALIDATED, TASK_STATES.CANCELLED, TASK_STATES.FAILED, TASK_STATES.BLOCKED])],
  [TASK_STATES.PLAN_VALIDATED, new Set([TASK_STATES.EXECUTING, TASK_STATES.PAUSED, TASK_STATES.CANCELLED, TASK_STATES.FAILED, TASK_STATES.BLOCKED])],
  [TASK_STATES.EXECUTING, new Set([TASK_STATES.TESTING, TASK_STATES.REPAIRING, TASK_STATES.PAUSED, TASK_STATES.CANCELLED, TASK_STATES.FAILED, TASK_STATES.BLOCKED])],
  [TASK_STATES.TESTING, new Set([TASK_STATES.REVIEWING, TASK_STATES.REPAIRING, TASK_STATES.CANCELLED, TASK_STATES.FAILED, TASK_STATES.BLOCKED])],
  [TASK_STATES.REVIEWING, new Set([TASK_STATES.VERIFYING, TASK_STATES.REPAIRING, TASK_STATES.CANCELLED, TASK_STATES.FAILED, TASK_STATES.BLOCKED])],
  [TASK_STATES.REPAIRING, new Set([TASK_STATES.EXECUTING, TASK_STATES.TESTING, TASK_STATES.VERIFYING, TASK_STATES.CANCELLED, TASK_STATES.FAILED, TASK_STATES.BLOCKED])],
  [TASK_STATES.VERIFYING, new Set([TASK_STATES.COMPLETED, TASK_STATES.REPAIRING, TASK_STATES.CANCELLED, TASK_STATES.FAILED, TASK_STATES.BLOCKED])],
  [TASK_STATES.PAUSED, new Set([TASK_STATES.EXECUTING, TASK_STATES.PLANNING, TASK_STATES.CANCELLED, TASK_STATES.FAILED])],
  [TASK_STATES.BLOCKED, new Set([TASK_STATES.PLANNING, TASK_STATES.EXECUTING, TASK_STATES.CANCELLED, TASK_STATES.FAILED])],
  [TASK_STATES.COMPLETED, new Set([])],
  [TASK_STATES.FAILED, new Set([TASK_STATES.CREATED, TASK_STATES.PLANNING])], // retry support
  [TASK_STATES.CANCELLED, new Set([])],
]);

function canTransition(fromState, toState) {
  if (!fromState || !toState) return false;
  if (fromState === toState) return true;
  const allowed = ALLOWED_TRANSITIONS.get(fromState);
  return allowed ? allowed.has(toState) : false;
}

function validateTransition(fromState, toState) {
  if (!canTransition(fromState, toState)) {
    throw new Error(`Invalid task state transition: ${fromState} -> ${toState}`);
  }
}

module.exports = {
  TASK_STATES,
  TERMINAL_STATES,
  canTransition,
  validateTransition,
};
