const fs = require("fs");
const path = require("path");
const { v4: uuidv4 } = require("uuid");
const { getAIResponse } = require("./ai");
const { uploadToGofile } = require("./gofileUpload");

const TEMP_DIR = path.join(__dirname, "../../temp");
const MAX_FILES = 12; // hard ceiling per build — keeps requests bounded and Groq-token-realistic
const PLAN_TIMEOUT_FILES = 6; // above this, build happens in two AI calls instead of one

// ── Step 1: Plan ──────────────────────────────────────────────
// Asks the AI to design a file structure for the requested app.
// Returns a list of { path, description } — no code yet, just the skeleton.
async function planProject(request, senderName) {
  const prompt = `You are a senior software architect. A user wants this built: "${request}"

Design a file structure for this as a small, realistic project (NOT Hogwarts Legacy — keep scope to something genuinely buildable: a calculator, a todo app, a small landing page, a simple API, a basic game, a small Discord/WhatsApp bot module, etc).

Respond ONLY with a JSON array, no other text, no markdown fences. Each item: {"path": "relative/file/path.ext", "description": "what this file does"}.
Max ${MAX_FILES} files. Include only files genuinely needed — no filler.

Example output:
[{"path":"index.html","description":"Main HTML structure with calculator UI"},{"path":"style.css","description":"Styling for the calculator"},{"path":"script.js","description":"Calculator logic and button handlers"}]`;

  const response = await getAIResponse(prompt, senderName, [], null, "");

  try {
    // Strip markdown fences if present, then extract just the [...] array portion
    // in case the model added explanatory text before/after it despite instructions
    let cleaned = response.replace(/```json|```/g, "").trim();
    const arrayMatch = cleaned.match(/\[[\s\S]*\]/);
    if (arrayMatch) cleaned = arrayMatch[0];

    const files = JSON.parse(cleaned);
    if (!Array.isArray(files) || files.length === 0) throw new Error("Empty plan");
    return { success: true, files: files.slice(0, MAX_FILES) };
  } catch (err) {
    console.error("Plan parsing failed:", err.message, "Raw response:", response.slice(0, 300));
    return { success: false, error: "Couldn't plan this project. Try describing it more simply, e.g. 'a todo app in HTML/CSS/JS'." };
  }
}

// ── Step 2: Generate code for each planned file ──────────────
async function generateFileContent(filePlan, projectContext, senderName) {
  const prompt = `You're building a small project. Here's the overall plan:
${projectContext}

Now write the COMPLETE content for this specific file: *${filePlan.path}*
Purpose: ${filePlan.description}

Rules:
- Write the full file content, no placeholders, no "// rest of code here"
- No explanations, no markdown fences — just the raw file content
- Make sure it actually works with the other files in the project (consistent imports, naming, etc)`;

  const response = await getAIResponse(prompt, senderName, [], null, "");
  // Strip markdown fences if present despite instructions
  return response.replace(/^```[\w]*\n?/, "").replace(/```$/, "").trim();
}

// ── Step 3: Build the whole project end-to-end ────────────────
async function buildProject(request, senderName, onProgress) {
  const planResult = await planProject(request, senderName);
  if (!planResult.success) return planResult;

  const files = planResult.files;
  const projectContext = files.map((f) => `- ${f.path}: ${f.description}`).join("\n");

  if (onProgress) await onProgress(`📋 Planned ${files.length} files. Generating code...`);

  const buildId = uuidv4();
  const projectDir = path.join(TEMP_DIR, `project_${buildId}`);
  fs.mkdirSync(projectDir, { recursive: true });

  const generatedFiles = [];

  for (let i = 0; i < files.length; i++) {
    const filePlan = files[i];
    if (onProgress && files.length > 3) {
      await onProgress(`⚙️ Generating ${i + 1}/${files.length}: ${filePlan.path}`);
    }

    try {
      const content = await generateFileContent(filePlan, projectContext, senderName);
      const fullPath = path.join(projectDir, filePlan.path);
      fs.mkdirSync(path.dirname(fullPath), { recursive: true });
      fs.writeFileSync(fullPath, content, "utf8");
      generatedFiles.push(filePlan.path);
    } catch (err) {
      console.error(`Failed to generate ${filePlan.path}:`, err.message);
      // Continue with other files rather than failing the whole build over one file
    }
  }

  if (generatedFiles.length === 0) {
    cleanupDir(projectDir);
    return { success: false, error: "Failed to generate any files. Try a simpler request." };
  }

  // Add a basic README describing the project
  const readmeContent = `# ${request}\n\nGenerated by ARIA.\n\n## Files\n${generatedFiles.map((f) => `- ${f}`).join("\n")}\n`;
  fs.writeFileSync(path.join(projectDir, "README.md"), readmeContent, "utf8");
  generatedFiles.push("README.md");

  if (onProgress) await onProgress("📦 Packaging project...");

  // Zip it
  const zipPath = path.join(TEMP_DIR, `${buildId}.zip`);
  const zipResult = await zipDirectory(projectDir, zipPath);
  cleanupDir(projectDir);

  if (!zipResult.success) {
    return { success: false, error: zipResult.error };
  }

  if (onProgress) await onProgress("☁️ Uploading...");

  const uploadResult = await uploadToGofile(zipPath, `${slugify(request)}.zip`);
  fs.unlinkSync(zipPath);

  if (!uploadResult.success) {
    return { success: false, error: `Built successfully but upload failed: ${uploadResult.error}` };
  }

  return {
    success: true,
    fileCount: generatedFiles.length,
    files: generatedFiles,
    downloadUrl: uploadResult.downloadPage,
  };
}

function zipDirectory(sourceDir, outPath) {
  return new Promise((resolve) => {
    const { exec } = require("child_process");
    exec(`cd "${sourceDir}" && zip -r "${outPath}" .`, (err, stdout, stderr) => {
      if (err) {
        console.error("Zip error:", stderr);
        resolve({ success: false, error: "Failed to package the project." });
      } else {
        resolve({ success: true });
      }
    });
  });
}

function cleanupDir(dir) {
  try {
    fs.rmSync(dir, { recursive: true, force: true });
  } catch (err) {
    console.error("Cleanup failed:", err.message);
  }
}

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "").slice(0, 40) || "project";
}

module.exports = { buildProject };
